### ISSUE TITLE
Add Proguard rules for models to prevent NullPointerException

### ISSUE THREAD

**Issue by iVoider** [basshelal/UnsplashPhotoPicker#11]
I'm recieving `Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference` inside `UnplashPickerAdapter.onBindViewHolder()` with `minifyEnabled true`.

Solution:

```
-keep class com.github.basshelal.unsplashpicker.data* {*;}
-keepclassmembers class com.github.basshelal.unsplashpicker.data* {
    <fields>;
    <init>();
    <methods>;
}
```

**Comment by basshelal** [comment]
Ah cheers for that, I suffer and struggle a lot with Progaurd and its funky nonsense!
Would you like to make a pull request with the fix? I'll have a look at it and merge it
Many thanks 😊
